### ISSUE TITLE
Document recommended image settings

### ISSUE THREAD

**Issue by nayr1991** [lanrat/homeplate#6]
Hey,

I was wondering if you would be willing to document the config you used for hass-lovelace-kindle-screensaver.
I'm having issues with the image captured from mine looks extremely washed out on my inkplate, regardless of the greyscale setting I use.

I have updated the waveform on my device, which was a slight improvement, but there's still a noticeable difference when flicking between the homeplate info screen and the lovelace image

**Comment by lanrat** [comment]
Hi,

I've since moved to using my fork (https://github.com/lanrat/hass-screenshot) which is very similar but adds a few fixes.

Here is the relevant part from my `docker-compose.yml` file for my Inkplate10.

```yml
  hass-screenshot:
    container_name: hass-screenshot
    image: lanrat/hass-screenshot
    build: hass-screenshot
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      - TZ=America/Los_Angeles
      - HA_BASE_URL=http://172.17.0.1:8123
      - HA_ACCESS_TOKEN=*************
      - LANGUAGE=en
      - MQTT_SERVER=192.168.1.4
      - REAL_TIME=true
      - RENDERING_DELAY=2
      - COLOR_MODE=GrayScale
        # image 1
      - HA_SCREENSHOT_URL=/lovelace-infra/hud?kiosk
      - RENDERING_SCREEN_HEIGHT=825
      - RENDERING_SCREEN_WIDTH=1200
      - GRAYSCALE_DEPTH=3
        # image 2+
        # .....
    restart: unless-stopped
    ports:
      - 5000:5000
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:5000/ || exit 1"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 60s
```

Let me know if you have any other questions.
